### ISSUE TITLE
Implement extraction of system multi-time correlations from the process tensor

### ISSUE THREAD

**Issue by gefux** [tempoCollaboration/OQuPy#105]
Implement extraction of system multi-time correlations from the process tensor. This is a generalisation of #31.

**Comment by rmadw** [comment]
Hi @gefux and @piperfw, 

As we discussed, I have modified  `contraction.py`  to incorporate the  `compute_nt_correlations`  code, and such that the original `compute_correlations` function now calls `nt_correlations` to compute both ordered and anti-ordered correlations.

Rather than having `compute_correlations` call `compute_nt_correlations` multiple times to deal with the time ordering, I slightly modified how  `compute_nt_correlations`  deals with overlapping time arguments of the last and second-to-last operator applied to the density matrix. Now, `compute_nt_correlations`  does essentially the same thing as the original `compute_nt_correlations`  for 2 operators, and an anti-time ordered two-time correlation can be calculated as follows:

```
def compute_correlations(.......)

#..........

    if time_order == "ordered":
        ops_order = ["left", "left"]
        dipole_ops = [operator_a, operator_b]
        ops_times = [times_a, times_b]
    if time_order == "anti":
        ops_order = ["right", "left"]
        dipole_ops = [operator_b, operator_a]
        ops_times = [times_b, times_a]
    
    corr = compute_nt_correlations(ops_order = ops_order,
                                   .......,
                                  .........)
    return corr
```
Lastly, I have also written a tutorial to accompany the code. I have all my changes/additions on a fork, and I'll do a pull request if all of this sounds good!

-Roos

**Comment by rmadw** [comment]
Thanks a lot for the feedback @piperfw! I get what you mean with the for loop about the time ordering in `compute_nt_correlations`, that indeed looks a lot simpler / more clear. I'll update that bit in the code right now and will make sure it still works as expected.

Thank you for looking at the tutorial as well, I did not think about using `dtype=complex` for the numpy arrays; that definitely makes it a bit easier to read. I'll fix the other typos/misalignments as well.

Let me know if there's anything else I can modify/clarify!

**Comment by piperfw** [comment]
Hi @rmadw,
Thanks for doing the changes so quickly!
Would you be able to give me write access to your fork, there are a few tweaks I would like to push.
After that I have a few comments but then we can make a PR I think.

**Comment by rmadw** [comment]
No problem @piperfw, let me know if you have write access now!

**Comment by piperfw** [comment]
Haha I was going to add a sentence explaining the time arguments, that's great.
Can you remind me, are you manually generating the `.rst` file for the docs from `.ipynb`?  I can never remember what the procedure is.

No idea why the first box of the `Background - 2D...` section appears with lots of empty scrolable space, maybe that's just me

I feel like we can remove the (possibly) qualifier from statement of non-Markovian dynamics in the first box, but it's probably not important.

---

Regarding the code, I made two small changes to the progress loop (L753) and the schedule function (L827) for conciseness. These shouldn't change anything, but you may like to double check you agree @rmadw 

---

Here are what I think needs doing before we can merge this into OQuPy:
- docs: `how_to_cite.rst`, `bibliography.rst` (including bibtex) and `index.rst` need to be updated with your preprint. I've added a line to `index.rst` for your contribution; feel free to edit this description as you see fit (`tox -e docs` to build docs, then e.g. `firefox docs/_build/html/index.html` to view)
- tests: these are currently failing due to errors; use `tox -e py36` from the repository base directory to run all tests. I assume you probably want to edit or remove the comparison against compute_tt(?)_correlations in `coverage/contractions_test.py` (if edit: probably put this in the physics test; coverage is mainly for basic input/output type checking etc.). Btw the other added tests are really good, because I don't think any two-time correlations functionality was covered before, so a vast improvement
- someone (could be me later) needs to make the linter happy, which mainly amounts to removing trailing whitespace - `tox -e style` to check this

**Comment by rmadw** [comment]
Hi @piperfw 

Thanks for the additional comments! And I realised I hadn't changed everything about the tutorial you gave feedback on, sorry about that!

To convert from `.ipynb` to `.rst`, I used the command `jupyter nbconvert --to rst n_time_correlations.ipynb`. Not sure if this is the best / most efficient way to do it though, I just googled haha.

I'm not getting any strange empty scrollable space in the tutorial like you're seeing, is this in the `.ipynb` file itself?

And for the changes you made in the code, thanks for doing that and that all looks great to me!

Finally for the last few points of things that need to be changed:
- I've added my preprint to the files you suggested.
- I fixed the tests, or least `tox -e py36` is working for me now and is giving a pass when I run it from the base repository. 
- I'll have a look at the trailing whitespace right now; am happy to fix that! (And will push all the changes above to the remote after that).

**Comment by piperfw** [comment]
> used the command jupyter nbconvert --to rst n_time_correlations.ipynb
This is the normal way I believe. Alas, it requires pandoc which in turn depends on about 200 haskell packages which I don't fancy installing on my computer for one use :laughing: 

Looks like the scrollable space could just be an issue with the (my) browser render of the view on GitHub, so a non-issue
![2024-03-05-06:25:26](https://github.com/tempoCollaboration/OQuPy/assets/29196860/3f4446d0-cae9-4e06-b025-6ffe71ffd595)

And great, once you've pushed the changes if you make a pull request to `dev-v0.5` of OQuPy when you have, that will allow me and Gerald to review it (also the automatic testing will confirm e.g. `tox -e py36` is good)
