### ISSUE TITLE
Can it support a coupling form that conserves the number of excitations？

### ISSUE THREAD

**Issue by ZhiGuangLu** [tempoCollaboration/OQuPy#141]
Besides this coupling form:  
$H_{\rm int}=\hat{S}\sum_{k}{\left(g_k\hat{b}_k^{}+g_k^*\hat{b}_k^\dagger\right)},$

another commonly used approach is the Jaynes-Cummings (JC) coupling form, i.e.,
$H_{\rm int}=\sum_{k}{\left(g_k\hat{S}^\dagger\hat{b}_k^{}+g_k^*\hat{b}_k^\dagger\hat{S}\right)},$
where $\hat{S}$ can be the annihilation operator or lowering operator.

However, the code “`occupy.Bath(S, correlations)`” only supports the former coupling form. Is it possible to modify the source code to support the second coupling form? Thanks.

**Comment by piperfw** [comment]
Hi @ZhiGuangLu, you are correct that the coupling of a Hermitian operator to the bath modes as in the first form you write is supported by OQuPy. Unfortunately, I am not aware that this is straightforward to generalise to the suggested JC coupling, since the method used by OQuPy is tied to the Gaussian bath with coupling of the Caldeira—Legget type I believe (for which it is possible to eliminate the environment variables explicitly when tracing out the environment - then Feynman-Vernon influence functional).

Another open system method you might consider is ACE (https://www.nature.com/articles/s41567-022-01544-9), which supports more general environment setups and is also open source (https://github.com/mcygorek/ACE). Potential future development may bring some features from / compatibility with ACE, but not soon.

**Comment by ZhiGuangLu** [comment]
@piperfw Thank you very much for your reply.

**Comment by piperfw** [comment]
No problem @ZhiGuangLu, I will close the issue now as out of current scope, but it is noted that there is interest in solving problems with this kind of coupling.
