### ISSUE TITLE
Tutorial to TEMPO parameter choice & the dkmax anomaly

### ISSUE THREAD

**Issue by gefux** [tempoCollaboration/OQuPy#23]
We should have a dedicated tutorial for finding good convergence parameters. In particular we should incorporate our new insights into how and when a larger `dkmax` can in fact make the computation faster. 
This will probably also affect the parameter guessing function.

@piperfw : would you be happy to share some of your wisdom on this here in this issue at some point?

**Comment by piperfw** [comment]
Yes, this is a good task for me. In fact, I was discussing this problem today, and possibly something we might want to look into (probably a wish list item for now): if we understand the issue of too small `dkmax` as an artefact of introducing a discontinuity into the bath autocorrelation function, could we somehow instead impose a smooth cut-off to avoid it?

I agree the choice of parameters is a most important topic, being I think the 'hardest' thing to get right when using (PT)-TEMPO (on the other hand, it couldn't be easier to get wrong - just chose at random!). Since I have quite a bit of experience in making PTs for at least one problem, I think I would have some insight to share. I'm currently focusing on paper writing but hope to have time in December to work on mean-field tempo and contribute to this tutorial.

To get the ball rolling, I think a crucial warning is that suitable convergence parameters for TEMPO are not necessarily suitable for PT-TEMPO (or vice versa). That is, the right choice of computational parameters depends on the numerical implementation not just the physical system. This has caught me out several times before now and I think would be an easy trap for new users to fall into.

**Comment by piperfw** [comment]
@gefux have you had any thoughts on how this tutorial should be phrased?

Thinking aloud, a difficultly is having a system for which is converge is possible with very limited (notebook/binder) resources. One way around that would be to tackle the convergence in two stages:

1.  Say you are interested in the very short time dynamics of a model (e.g. decay of a quantum dot), so dkmax is not set, and demonstrate convergence under dt and precision
2. Do the same/similar model but late time-dynamics (motivation e.g. accurately determine a steady-state), to explain convergence of dkmax in a setting where the time resolution dt does not need to be small.

After 1. & 2., say in general convergence under the parameters has to be considered simultaneously. And `guess_tempo_parameters` _may_ provide a reasonable starting point.

- Both of those could be done with a spin boson model (which I understand has the property that the size of dt does not affect the accuracy of the dynamics).
- It would be nice to address #96 for this 

The above could be done with the TEMPO method. Then, note the PT computation may require different convergence parameters. 
Finally, a comment could be made regarding the 'dkmax anomaly'. I would want to establish whether that is straightforward to show for PTs with easy-to-compute parameters (I observed the issue when making long PTs with very high precisions).
