### ISSUE TITLE
why is the performance of tempo slower than the old version when the Hamiltonian is time-dependent?

### ISSUE THREAD

**Issue by antonio1151** [tempoCollaboration/OQuPy#45]
Hi Tempo developers, 

I have been using the version of TEMPO given in Nat. Commun. 9, 3322 (2018) which I modified in order to use time-dependent Hamiltonians. I just found out that you released this version of TEMPO which is able to use TD-Hamiltonians.  Therefore, I used it in a toy model of a two-level system interacting with two laser pulses and a bath represented for a superohmic spectral density (with zeta=2, but I introduced it using correlations.CustomSD since I am planning to use my own spectral density).  After the calculation was done, I noticed that the computation time using this new version is 4 to 5 times slower than the old version.  I was wondering if this is normal or maybe because I am missing something in the implementation of the new version. 

this is how I am doing the implementation:
system = tempo.TimeDependentSystem(hamil) 
correlations = tempo.correlations.CustomSD(jw,wc,temperature=T)
bath = tempo.Bath(sigmaz/2.0, correlations) # I use numpy matrices to define the operators 
tempo_parameters = tempo.TempoParameters(dt=0.1, dkmax=100, epsrel=10**(-4))
tempo_sys = tempo.Tempo(system=system,
                        bath=bath,
                        initial_state=psi_tls,
                        start_time=0.0,
                        parameters=tempo_parameters)
dynamics = tempo_sys.compute(end_time=tf)

**Comment by gefux** [comment]
Hi Antonio,
Thank you for the question. There are some differences in the functionality between the  Nat. Commun. 9, 3322 (2018) and this package which should produce more accurate results but also might cause a longer computation time. Which means one would have to compare accuracy of the results vs. computation time to truly judge the performance. Currently, the differences are:

1. epsrel is the relative tollerance for the 2 norm of all truncated singular values (vs. Nat. Commun. truncates all singlar values that are a factor of epsrel smaller than the largest singular value). This means that (depending on the actual singular value distribution) one could choose a larger epsrel in this package to get the same behaviour as in the Nat. Commun. code.
2. the Nat. Commun. code  does not include the influence functionals that "integrate back to zero" (see. http://dx.doi.org/10.1088/1367-2630/aa8744) and #9 . You can create the same behaviour in this package if you set: `max_correlation_time=10.1` when creating the correlations. It's 10.1 because dt*(dkmax+1) = 10.1 in your example. I admit that this might be quite confusing. We are working on making this  more transperant here #13 .

**Comment by antonio1151** [comment]
I will leave a copy of my input. I want to point out that this is just a toy model I used to learn how to implement this new version of tempo, then, the parameters are random.

Additionally, I would like to ask if is possible to get rid of the cutoff_type in correlations.CustomSD so I can use spectral density Drude-Lorentz type .

#conversion parameters
leng=1.973E+3  #from Angstrom to natural units
time_nor_nat=0.6582 #from natural units to fs
electr_nor_nat=0.4328E-4 #from V/A to natural units
e_nor_nat=11.71 #from e to natural units
hbar=0.6582
pi=np.pi
####################################
####################################
#setting the TLS
Delt=1.94   #energy gap between the two level
n_tls=2
#Pauli matrices
sigmaz=np.diag([1,-1])
sigmax=np.array([[0,1],[1,0]])
###Electric field parameters
wl=2.0  #frequency
e0=0.05/electr_nor_nat #field amplitude
tau=4.246/time_nor_nat#
t01=20.0/time_nor_nat #center of the first pulse
t02=60.0/time_nor_nat  #center of the second pulse
phi=pi*0.0
mu01=1/(leng*e_nor_nat)

##############################################
##Initial conditions

psi_tls=np.diag([0,1])  #intial condition TLS
#########################################
##pulses
def Elec(t):
    exp1=np.exp(-((t-t01)/(tau*np.sqrt(2.0)))**2)
    sin1=((t-t01)/tau**2)*np.sin(wl*(t-t01)+phi)-wl*np.cos(wl*(t-t01)+phi)
    exp2=np.exp(-((t-t02)/(tau*np.sqrt(2.0)))**2)
    sin2=((t-t02)/tau**2)*np.sin(wl*(t-t02)+phi)-wl*np.cos(wl*(t-t02)+phi)
    return (e0/wl)*(sin1*exp1+sin2*exp2)
######################################################
##Hamiltonian
def hamil(t):
    hh=(Delt)*sigmaz-mu01*Elec(t)*sigmax
    return hh
##################################################
#bath
T=298  #temperature
alpha=0.0005 
wc=0.1283 #frequency cutoff
## spectral function
def jw(w):
    return alpha*w**2*np.exp(-w/wc)/wc

#################################
#setting tempo
#sytem
system = tempo.TimeDependentSystem(hamil)
#spectral density
correlations = tempo.correlations.CustomSD(jw,wc,temperature=T)

#bath
bath = tempo.Bath(sigmaz/2.0, correlations)

#paramaters of the dynamics
#paramaters dynamics
tf=100/time_nor_nat
dt=0.1
points=int(tf/dt)
k=int(100) #cutoff

tempo_parameters = tempo.TempoParameters(dt, dkmax=k, epsrel=10**(-4))
#dynamics
tempo_sys = tempo.Tempo(system=system,
                        bath=bath,
                        initial_state=psi_tls,
                        start_time=0.0,
                        parameters=tempo_parameters)
dynamics = tempo_sys.compute(end_time=tf)

**Comment by gefux** [comment]
Thank you for sharing that. Let's try to keep this issue mostly about comparing the computation time of the Nat. Comm. code with this package. If you have any other issues coming up, please feel free to create another issue (I just did that for your cutoff_type question).

One thing that jumps into my eye is that as it is the code you shared would effectively have a cutoff looking like exp(-2w/wc) , i.e. you have half the cutoff frequency as you probably expect because you explicitly have an exponential cutoff at wc in your `jw` function **and** the default exponential cutoff in the CustomSD class. Circumventing the discussion whether that is a good default parameter of the CustomSD class (which we should discuss in issue #46) this will certainly affect computation time (because it affects the physics). Thus this would now be a third reason (in addition to the two of my previous post) for why the comparison of the computation times would not be meaningful.

I'll try to have a go and try to compare the computation times of Nat. Comm. and this package for the physical model you describe above, taking the three differences mentioned above into account. I will probably not get round to this before the end on next week. If you have any results on that, please feel free to share them!
