### ISSUE TITLE
Mean-field schematic in overview.svg

### ISSUE THREAD

**Issue by piperfw** [tempoCollaboration/OQuPy#58]
To accompany the introduction of TEMPO with field we might add a diagram illustrating the functionality to overview.svg as currently appears in the readme. 

A mock-up of the schematic typically used to depict the mean-field system in the same style is attached. The central red node represents the field (currently denoted alpha, but perhaps a waveform could be used instead) and the reference is [[9]](https://arxiv.org/abs/2112.09003).

![text137437](https://user-images.githubusercontent.com/29196860/153754309-0491d593-2b92-4fac-8596-268df3e9b656.png)

**Comment by gefux** [comment]
I've used this graphic in a meeting at the UnitaryFund. 
![mean-field](https://user-images.githubusercontent.com/38002396/154955867-c6aedd9d-8f1c-4def-9de2-c9a5e0a1a612.svg)

I think, however, we should find some graphic that is less space consuming. Maybe pushing all the system and environments into an arch of, say 90deg instead of the current 360deg?

**Comment by piperfw** [comment]
I think the space-saving graphic is great and doesn't compromise the accuracy of the schematic.

**Comment by piperfw** [comment]
This was added in [96738dd](https://github.com/tempoCollaboration/OQuPy/commit/96738dd370c5bb7d9c3d7f70c0a8953f7af52753)
