### ISSUE TITLE
Move to Python 3.8

### ISSUE THREAD

**Issue by piperfw** [tempoCollaboration/OQuPy#80]
Python 3.6 reached its end-of-life (official support) back in Sep 2021. While this itself may not cause issues, it limits the numpy and scipy versions we can use to 1.19.X and 1.5.X respectively (2020). Both packages have evolved considerably since then, and future developers may want access to the latest features.

Since the current Ubuntu LTS ships with Python 3.10, I would suggest targeting 3.10 for builds. The end-of-life for this Python version is scheduled for Oct 2026.

**Comment by gefux** [comment]
I fully agree. Don't ask me why I started this project with python 3.6. :)
Doing this should only really be a matter of changing:

- `setup.py`
- `tox.ini`
- `CONTRIBUTING.md`

**Comment by gefux** [comment]
I guess we could then publish this as a bug-fix version OQuPy 0.4.1

**Comment by piperfw** [comment]
Is there a particular reason tensornetwork is locked to 0.4.3? The latest is 0.4.6, although it doesn't look like the project is active anymore.

**Comment by gefux** [comment]
Yes: I've tried higher versions of tensornetwork before but something failed (I forgot what exactly), so I've been lazy and fixed the version. I guess it's less problematic to lock the version with tensornetwork than with numpy. There is of course still the bigger question about what to do about the death of tensornetwork (see #78).

**Comment by piperfw** [comment]
Yes, I just discovered that :'D. But the good news is that using 3.10 doesn't appear to break anything in the examples or tutorials, so I think it may be as simple as changing the files you list above, although something could still crop up when testing and building.

That's a shame about tensornetwork. I agree locking the version should be less problematic for now.

**Comment by gefux** [comment]
Actually, coming to think about it again: There is value in using the lowest python version that works without any problem (other packages do that too) because otherwise we unnecessarily force the user to install a python 3.10 although their e.g. python 3.8 installation would work just fine. How about we settle on python3.8 for now and move up to 3.10 whenever necessary?

**Comment by piperfw** [comment]
Haha, I think this exact same reasoning I used for 3.10 - use the version that would force the fewest amount of new users to install a different python version. But I'm happy with 3.8; the important thing is being able to use supported numpy etc. packages (3.8 planned to be supported until 2024).

**Comment by gefux** [comment]
If a user has python 3.10 installed they wouldn't have to install 3.8 in that case because (as the versioning suggests) it is backwards compatible. Anything that runs on version 3.x should also run on version 3.y if x<=y. Hence the best thing is to use the smallest version that works well as the minimal requirement. I've been maybe a bit optimistic with version 3.6 at the start of the project.
Does this make sense?

**Comment by piperfw** [comment]
Yes, well explained - thanks

**Comment by piperfw** [comment]
@gefux I think we run of the risk of things getting unnecessarily complicated if we try build against multiple Python versions, since both numpy and scipy have different ranges of support for each Python version (see table on [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)). 

For example, numpy indicates support for py3.8 from version 1.19, so we should use numpy>=1.19.0, but the minimum supported version for 3.9 is instead 1.21.0. So we would have to have a separate list of dependencies for each python build - fine in tox.ini, but a bit messy to have multiple requirement files for developers to install from?

I propose either going for the minimum python version that supports the latest numpy/scipy versions, that's 3.8 as you suggest, or going for the latest widely adopted python version, 3.10.
I actually would tend towards the latter, as numpy may drop support for python3.8 from as early as April next year, although we can always do another version bump then.

**Comment by gefux** [comment]
I see your point. However, I am a bit confused now about your original issue #81. It seems to me that if numpy 1.19.4 works with py3.6 and 1.19.5 does not, then numpy 1.19.4 (not 1.19.5) should be the last version supported on py3.6. Then given that we specify numpy>1.19.0 there would be no problem because under py36 numpy 1.19.4 would be installed and under py39 numpy >= 1.21.0 would be installed, etc.
It seems to me that the principle of requiring the smallest version numbers possible would make sense but we might be dealing with a numpy "anomaly" here. 
I feel I need to consult some best practice descriptions and see  how good projects deal with this. I'll get back to you.

**Comment by piperfw** [comment]
Ah apologies, when I was looking at `tox.ini` this morning it hadn't clicked that package dependencies would be resolved automatically according to the current python version, that's very nice. I don't see issue with your suggestion then, but equally would be interested to hear if you look into best practices on this.

numpy 1.19.5 is an anomaly, since it _is_ officially supported by py36 only it had a critical bug in the linlag.py sub module it seems. But I realise we can just add `!1.19.4` to exclude that particular version, then in other all other cases the versioning with e.g. `>1.19.0` should work.

**Comment by gefux** [comment]
Looking around a bit I find plenty of projects that use py3.6+ with numpy 1.19.0+ without any problem, for example qutip. This suggests that there might be something wrong with our code in issue #81. I reopen that issue. Let's get the issue #81 sorted first.

**Comment by gefux** [comment]
As discussed in issue #81 it seems that the original motivation to possibly restrict the python versions to 3.8+ is specific to some outdated pip version. I don't think this sufficiently justifies to enforce a higher python version.
