### ISSUE TITLE
_apply_caps fails for MeanFieldDynamics with non-trivial Control

### ISSUE THREAD

**Issue by piperfw** [tempoCollaboration/OQuPy#83]
Adding a control operations to `computer_dynamics_with_field` appears to break the calculation in `_apply_caps` when constructing the list of state tensors for the step at which the control operation is applied.

A minimal example is attached. I am not familiar with the Control class so worth checking this is not just a syntax/user logic error (I observed the same control operation does work with a non-mean-field calculation however).

[mwe.txt](https://github.com/tempoCollaboration/OQuPy/files/10208595/mwe.txt)

**Comment by gefux** [comment]
Sorry for the massive delay -- I've totally overlooked this issue.
There was a silly technical coding mistake there which I believe I fixed with #84. I've also added your example as a test.
@piperfw : Would you check whether this solves the issue you've been having. If it does, you can close the issue. Best ~gefux

**Comment by piperfw** [comment]
Hi @gefux, just to follow up, I've tested some less trivial examples today and everything appears to be working as expected. Thanks!

I suppose it would be nice to have a `.compute_correlations_with_field` analogous to `.compute_correlations` - probably something I can issue and assign to myself (or whoever gets there first) when I next have time aside for some development.
